Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.hostmanager.enabled = true
  
  if Vagrant.has_plugin?("vagrant-timezone")
    config.timezone.value = "UTC"
  end

  (1..3).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.hostname = "node#{i}.example.com"
      node.vm.network :private_network, ip: "192.168.50.#{i+10}"
      node.vm.network "forwarded_port", guest: 8091, host: 8091 + i
      node.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
      end

      node.vm.provision "shell", inline: <<-SHELL
        mkdir -p /opt/couchbase/var/lib
        mkdir -p /opt/couchbase/var/data
        mkdir -p /opt/couchbase/var/index
        sudo apt-get update
        sudo apt-get install -y ntp
        echo "pool 0.ubuntu.pool.ntp.org iburst" | sudo tee -a /etc/ntp.conf
        echo "pool 1.ubuntu.pool.ntp.org iburst" | sudo tee -a /etc/ntp.conf
        sudo systemctl restart ntp
      SHELL
    end
  end
end
