Vagrant.configure("2") do |config|
  (1..3).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.box = "ubuntu/focal64"
      node.vm.hostname = "node#{i}"
      node.vm.network :private_network, ip: "192.168.50.#{i+10}"
      node.vm.network "forwarded_port", guest: 8091, host: 8091 + i
      node.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
      end
    end
  end
end
