---
- name: Gather facts
  setup:

- name: Update all packages to the latest version
  apt:
    name: "*"
    state: latest
  become: true

- name: Install necessary software packages
  apt:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - openssl
    - libssl1.1  # Use libssl1.0.0 for Ubuntu 16.04 or older
    - wget
    - gnupg
    - curl
    - python3-httplib2  # Assuming you're using Python3

- name: Configure swappiness
  sysctl:
    name: vm.swappiness
    value: '0'
    state: present
    sysctl_file: /etc/sysctl.conf
    reload: yes
  become: true

- name: Create a systemd service to disable THP
  copy:
    dest: /etc/systemd/system/disable-thp.service
    content: |
      [Unit]
      Description=Disable Transparent Huge Pages (THP)

      [Service]
      Type=simple
      ExecStart=/bin/sh -c "echo 'never' > /sys/kernel/mm/transparent_hugepage/enabled && echo 'never' > /sys/kernel/mm/transparent_hugepage/defrag"

      [Install]
      WantedBy=multi-user.target
    mode: '0644'
  become: true

- name: Reload systemd manager configuration
  systemd:
    daemon_reload: yes
  become: true

- name: Enable and start the service
  systemd:
    name: disable-thp
    enabled: yes
    state: started
  become: true

- name: Install gnupg
  apt:
    name: gnupg
    state: present
  become: true

