# Loop for creating Couchbase users
- name: Create Couchbase Users
  couchbase_user:
    hostname: "{{ ansible_default_ipv4.address }}"
    username: "{{ couchbase_admin_username }}"
    password: "{{ couchbase_admin_password }}"
    name: "{{ item.name }}"
    password_hash: "{{ item.password | password_hash('sha256') }}"
    roles: "{{ item.roles }}"
    state: present
  loop: "{{ couchbase_users }}"

# Loop for creating Couchbase buckets
- name: Create Couchbase Buckets
  couchbase_bucket:
    hostname: "{{ ansible_default_ipv4.address }}"
    username: "{{ couchbase_admin_username }}"
    password: "{{ couchbase_admin_password }}"
    bucket: "{{ item.name }}"
    bucket_type: "{{ item.type }}"
    memory_quota: "{{ item.memory_quota }}"
    index_memory_quota: "{{ item.index_memory_quota }}"
    query_memory_quota: "{{ item.query_memory_quota }}"
    state: present
  loop: "{{ couchbase_buckets }}"

# Loop for creating Couchbase collections
- name: Create Couchbase Collections
  couchbase_collections:
    hostname: "{{ ansible_default_ipv4.address }}"
    username: "{{ couchbase_admin_username }}"
    password: "{{ couchbase_admin_password }}"
    bucket: "{{ item.bucket }}"
    scope: "{{ item.scope }}"
    collection: "{{ item.name }}"
    state: present
  loop: "{{ couchbase_collections }}"
