- name: Reset Administrator password
  shell: >
    curl -X POST -u Administrator:password \
    http://127.0.0.1:8091/settings/web \
    -d password=new_password
  vars:
    new_password: "{{ admin_pw }}"  # Replace with the new Administrator password
