# roles/couchbase_cluster/tasks/configure_couchbase_cluster.yml

- name: Gather FQDN of node1
  shell: "hostname -f"
  register: fqdn_result
  when: inventory_hostname == groups['couchbase_servers'][0]

- name: Initialize Couchbase cluster on node1
  command: >
    /opt/couchbase/bin/couchbase-cli cluster-init
    --cluster={{ fqdn_result.stdout }}
    --cluster-username=admin
    --cluster-password={{ admin_pw }}
    --services={{ node_services[inventory_hostname] | default('data,index,query') }}
    --cluster-ramsize={{ cluster_ramsize | default('1024') }}
    --cluster-index-ramsize={{ cluster_index_ramsize | default('256') }}
    --index-storage-setting=memopt
  when: inventory_hostname == groups['couchbase_servers'][0]

- name: Add nodes to the Couchbase cluster
  command: >
    /opt/couchbase/bin/couchbase-cli server-add
    --cluster={{ fqdn_result.stdout }}
    --user=admin
    --password={{ admin_pw }}
    --server-add={{ hostvars[item].ansible_default_ipv4.address }}
    --services={{ node_services[inventory_hostname] | default('data') }}
    --server-add-username={{ node_username | default('admin') }}
    --server-add-password={{ node_password | default(admin_pw) }}
  loop: "{{ groups['couchbase_servers'][1:] }}"
  when: inventory_hostname != groups['couchbase_servers'][0]

