# deploy_couchbase.yml

- name: Deploy Couchbase Server
  hosts: couchbase_servers  # Replace with the appropriate host/group name from your inventory
  gather_facts: true
  become: true


  vars:
    # If you want to specify a specific build, you will need to locate the build version by uncommenting some lines in the 02_install task and use that specifier here. 
    couchbase_version: 7.2.0*
    admin_pw: Changeit
    node_services:
      node1.example.com: "data,query,index"  # Services to be installed on server 1
      node2.example.com: "data,query,index"  # Services to be installed on server 2
      node3.example.com: "data,query,index"  # Services to be installed on server 3
    cluster_ramsize: 1024  # Cluster RAM size in MB (can be overridden)
    cluster_index_ramsize: 256  # Cluster Index RAM size in MB (can be overridden)

    # Define dynamic lists of users, buckets, and collections
    couchbase_users:
      - username: testing_ansible 
        password: testing1234
        roles: admin

    couchbase_buckets:
      - name: beyond
        memory_quota: 512
        type: magma
        index_memory_quota: 256
        query_memory_quota: 256

    couchbase_collections:
      - name: system
        scope: cachelogs
      - name: system
        scope: cachesettings
      - name: user
        scope: override
      - name: user
        scope: permissions
      - name: etl
        scope: pricenodes
      - name: pnl
        scope: daily

  roles:
    - couchbase_server_prep
    - couchbase_server_install
    - couchbase_server_cluster_init

