# deploy_couchbase.yml

- name: Deploy Couchbase Server
  hosts: couchbase_servers  # Replace with the appropriate host/group name from your inventory
  gather_facts: true
  become: true


  vars:
    # If you want to specify a specific build, you will need to locate the build version by uncommenting some lines in the 02_install task and use that specifier here. 
    couchbase_version: 7.2.0-5325-1
    admin_pw: Changeit
    memory_quota: 1024
    index_memory_quota: 256
    node_services:
      node1.example.com: "data,query,index"  # Services to be installed on server 1
      node2.example.com: "data,query,index"  # Services to be installed on server 2
      node3.example.com: "data,query,index"  # Services to be installed on server 3
      node4.example.com: "data,query,index"  # Services to be installed on server 4
    node_service_paths:
      data: "/opt/couchbase/var/data" # This is where the data path will be set if the node is defined to have the data service in the node services block
      index: "/opt/couchbase/var/index" # This is where the index path will be set if the node is defined to have the index service in the node services block
    cluster_ramsize: 1024  # Cluster RAM size in MB (can be overridden)
    cluster_index_ramsize: 256  # Cluster Index RAM size in MB (can be overridden)
    index_settings:
      storage_mode: plasma
      replicas: 2
    couchbase_user_list:
      - username: testuser1
        password: ChangeMe1
        role: ro_admin
      - username: testuser2
        password: ChangeMe2
        role: ro_admin
      - username: index_manager
        password: ChangeMe3
        role: "query_manage_index[*]"


    #Don't add defer build to the query, the ansible task does that for us. 
    indexes:
      - bucket: "beyond"
        query: "CREATE INDEX `corr_id` ON `beyond`.`pnl`.`daily`(`corr_id`)"
      - bucket: "beyond"
        query: "CREATE INDEX `doc_type` ON `beyond`.`pnl`.`daily`(`doc_type`)"
      - bucket: "beyond"
        query: "CREATE INDEX `display_name` ON `beyond`.`user`.`permissions`(`display_name`)"
      - bucket: "beyond"
        query: "CREATE INDEX `job_type` ON `beyond`.`system`.`cachelogs`(`display_name`)"
      - bucket: "beyond"
        query: >
          CREATE INDEX `sub_type_product_trade_date_to_number_daily_pnl_doc_type` 
          ON `beyond`.`pnl`.`daily`(`sub_type`,`product`,`trade_date`,`daily_pnl`)
      - bucket: "beyond"
        query: >
          CREATE INDEX `trade_year_trade_date_doc_type` 
          ON `beyond`.`pnl`.`daily`(`trade_year`,`trade_date`) 
          WHERE (`doc_type` = 'invoiced-pnl')
      - bucket: "beyond"
        query: >
          CREATE INDEX `doc_type_sub_type_trade_year` 
          ON `beyond`.`pnl`.`daily`(`doc_type`, `sub_type`, `trade_year`) 
          PARTITION BY HASH (doc_type, sub_type, trade_year)


    couchbase_buckets:
      - name: beyond
        memory_quota: 1024
        storage_backend: magma
        bucket_type: couchbase
        bucket_ramsize: 500
        bucket_replica: 2
        compression_mode: "active"
        bucket_priority: high
        collections:
          - parent_scope: etl
            name: pricenodes
            maxTTL: 0
            history: "false"
          - parent_scope: pnl
            name: daily
            maxTTL: 0
            history: "false"
          - parent_scope: system
            name: cachelogs
            maxTTL: 864000
            history: "false"
          - parent_scope: system
            name: cachesettings
            maxTTL: 0
            history: "false"
          - parent_scope: user
            name: override
            maxTTL: 0
            history: "false"
          - parent_scope: user
            name: permissions
            maxTTL: 0
            history: "false"

  roles:
    - couchbase_server_prep
    - couchbase_server_install
    - couchbase_server_cluster_init
    - couchbase_bucket_setup
    - couchbase_user_setup
   
