- name: Create users block
  run_once: true
  delegate_to: "{{ play_hosts[0] }}"
  block:
    - name: Create users
      no_log: true # to prevent passwords from being exposed, do not log this task
      uri:
        url: http://{{ play_hosts[0] }}:8091/settings/rbac/users/local/{{ loop_user.username }}
        method: PUT
        user: "Administrator"
        password: "{{ admin_pw }}"
        force_basic_auth: true
        body_format: form-urlencoded
        body:
          password: "{{ loop_user.password }}"
          roles: "{{ loop_user.role }}"
        status_code: 200
      loop: "{{ couchbase_user_list }}"
      loop_control:
        loop_var: loop_user
