
- name: Check if the node is part of a cluster
  command: >
    /opt/couchbase/bin/couchbase-cli server-list
    --cluster={{ play_hosts[0] }}
    --username=Administrator
    --password={{ admin_pw }}
  register: server_list_result
  changed_when: false
  failed_when: >
    server_list_result.rc != 0 and
    "ERROR: unknown pool" not in server_list_result.stdout

- name: Couchbase CLI node-init -- Pre cluster-init
  command: >
    /opt/couchbase/bin/couchbase-cli node-init
      --cluster={{ inventory_hostname }}
      --username=Administrator
      --password={{ admin_pw }}
      --node-init-hostname={{ inventory_hostname }}
      {% set services = node_services[inventory_hostname]|default('')|split(',') %}
      {% if 'index' in services %}
      --node-init-index-path={{ node_service_paths['index']|trim }}
      {% endif %}
      {% if 'data' in services %}
      --node-init-data-path={{ node_service_paths['data']|trim  }}
      {% endif %}
      {% if 'analytics' in services %}
      --node-init-analytics-path={{ node_service_paths['analytics']|trim  }}
      {% endif %}
      {% if 'eventing' in services %}
      --node-init-eventing-path={{ node_service_paths['eventing']|trim  }}
      {% endif %}
  when: inventory_hostname not in server_list_result.stdout
  register: init_node_result
  retries: 10
  delay: 5
  until: init_node_result.rc == 0