# roles/couchbase_cluster/tasks/configure_couchbase_cluster.yml

- name: Initialize Couchbase cluster
  command: >
      /opt/couchbase/bin/couchbase-cli cluster-init 
        --cluster={{ inventory_hostname }} 
        --cluster-username=Administrator 
        --cluster-password={{ admin_pw }} 
        --services={{ node_services[inventory_hostname] | default('data,index,query') }} 
        --cluster-ramsize={{ cluster_ramsize | default('1024') }} 
        --cluster-index-ramsize={{ cluster_index_ramsize | default('256') }} 
        --index-storage-setting=memopt 
  delegate_to: "{{ play_hosts[0] }}"
  run_once: true
  register: cluster_init_result
  failed_when: "cluster_init_result.rc == 1 and 'ERROR: Cluster is already initialized, use setting-cluster to change settings' not in cluster_init_result.stdout"
