- name: Initialize Cluster First time -- reset_admin_pw
  include_tasks: reset_admin_pw.yml
- name: Initialize Cluster First time -- init_node
  include_tasks: init_node.yml
- name: Initialize Cluster First time -- init_cluster
  include_tasks: init_cluster.yml
- name: Initialize Cluster First time -- add_servers
  include_tasks: add_servers.yml
- name: Initialize Cluster First time -- rebalance
  include_tasks: rebalance.yml
- name: Initialize Cluster First time -- set memory quotas
  include_tasks: set_memory_quotas.yml
- name: Initialize Cluster First time -- update GSI settings
  include_tasks: set_index_settings.yml
