- name: Kick off rebalance on master node
  command: >
      /opt/couchbase/bin/couchbase-cli rebalance
        --cluster={{ inventory_hostname }}
        --username=Administrator
        --password={{ admin_pw }}
  when: inventory_hostname == groups['couchbase_servers'][0]
  register: cluster_rebalance_result
  #failed_when: "cluster_rebalance_result.rc == 1 and 'ERROR: Cluster is already initialized, use setting-cluster to change settings' not in cluster_rebalance_result.stdout"
