# roles/couchbase_server/defaults/main.yml

# Couchbase edition: "community" or "enterprise"
couchbase_edition: community

# Couchbase version, e.g., "7.2.0"
couchbase_version: 7.2.0

# Default Couchbase admin credentials
couchbase_admin_username: admin
couchbase_admin_password: mystrongpassword

# Default Couchbase user settings
couchbase_user_name: user1
couchbase_user_password_hash: "{{ couchbase_admin_password | password_hash('sha256') }}"
couchbase_user_roles: admin

# Default Couchbase bucket settings
couchbase_bucket_name: my_bucket
couchbase_bucket_memory_quota: 512
couchbase_bucket_index_memory_quota: 256
couchbase_bucket_query_memory_quota: 256

# Default Couchbase collection settings
couchbase_collections: []

# defaults file for couchbase_prep
ntp_package: ntp
swappiness_value: 0
ulimit_nofile_soft: 40960
ulimit_nofile_hard: 40960
ulimit_core_soft: unlimited
ulimit_core_hard: unlimited
