---
- name: Gather facts
  setup:

- name: Update all packages to the latest version
  apt:
    name: "*"
    state: latest
  become: true


- name: Configure swappiness
  sysctl:
    name: vm.swappiness
    value: '0'
    state: present
    sysctl_file: /etc/sysctl.conf
    reload: true
  become: true

- name: Create a systemd service to disable THP
  copy:
    dest: /etc/systemd/system/disable-thp.service
    content: |
      [Unit]
      Description=Disable Transparent Huge Pages (THP)

      [Service]
      Type=simple
      ExecStart=/bin/sh -c "echo 'never' > /sys/kernel/mm/transparent_hugepage/enabled && echo 'never' > /sys/kernel/mm/transparent_hugepage/defrag"

      [Install]
      WantedBy=multi-user.target
    mode: '0644'
    force: false # This will prevent this task from showing as changed if we are not - in fact - changing anything
  become: true
  register: disable_thp_result

- name: Reload systemd manager configuration
  systemd:
    daemon_reload: true
  become: true
  changed_when: disable_thp_result.changed

- name: Enable and start the service
  systemd:
    name: disable-thp
    enabled: true
    state: started
  become: true
  changed_when: disable_thp_result.changed

- name: Set ulimits for Couchbase
  pam_limits:
    domain: couchbase
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: 40960
  with_items:
    - { limit_type: 'soft', limit_item: 'nofile' }
    - { limit_type: 'hard', limit_item: 'nofile' }

- name: Set ulimits for Couchbase
  pam_limits:
    domain: couchbase
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: unlimited
  with_items:
    - { limit_type: 'soft', limit_item: 'core' }
    - { limit_type: 'hard', limit_item: 'core' }
    - { limit_type: 'soft', limit_item: 'memlock' }
    - { limit_type: 'hard', limit_item: 'memlock' }
