# tasks/main.yml

- name: Download Couchbase repository package
  get_url:
    url: https://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-amd64.deb
    dest: /tmp/couchbase-release-1.0-amd64.deb

- name: Ensure Couchbase repository package is installed
  become: true
  apt:
    deb: /tmp/couchbase-release-1.0-amd64.deb
    state: present
  register: couchbase_repo_install_result

- name: Update APT cache
  become: true
  apt:
    update_cache: yes
  changed_when: couchbase_repo_install_result.changed

- name: Print available Couchbase versions
  become: true
  shell: apt list -a couchbase-server
  register: couchbase_versions
  run_once: true
  delegate_to: "{{ play_hosts[0] }}"
  changed_when: false

- name: Display Couchbase versions
  debug:
    var: couchbase_versions.stdout
  run_once: true
  delegate_to: "{{ play_hosts[0] }}"

- name: Install Couchbase server package
  become: true
  apt:
    name: "couchbase-server={{ couchbase_version }}"
    state: present

- name: Wait for couchbase to be ready
  wait_for:
    port: 8091
    host: 127.0.0.1
    connect_timeout: 3
    delay: 3
    timeout: 30
